Unable to find executable: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304048/build/incorrect_solution_tests
UpdateCTestConfiguration  from :/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304048/build/DartConfiguration.tcl
UpdateCTestConfiguration  from :/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304048/build/DartConfiguration.tcl
Test project /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304048/build
Constructing a list of tests
Done constructing a list of tests
Updating test list for fixtures
Added 0 tests to meet fixture requirements
Checking test dependency graph...
Checking test dependency graph end
test 1
      Start  1: incorrect_solution_tests
Could not find executable /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304048/build/incorrect_solution_tests
Looked in the following places:
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304048/build/incorrect_solution_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304048/build/incorrect_solution_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304048/build/Release/incorrect_solution_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304048/build/Release/incorrect_solution_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304048/build/Debug/incorrect_solution_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304048/build/Debug/incorrect_solution_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304048/build/MinSizeRel/incorrect_solution_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304048/build/MinSizeRel/incorrect_solution_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304048/build/RelWithDebInfo/incorrect_solution_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304048/build/RelWithDebInfo/incorrect_solution_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304048/build/Deployment/incorrect_solution_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304048/build/Deployment/incorrect_solution_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304048/build/Development/incorrect_solution_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304048/build/Development/incorrect_solution_tests

1: Test command: 
1: Working Directory: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304048/build
 1/11 Test  #1: incorrect_solution_tests .........***Not Run   0.00 sec
test 2
      Start  2: model1_tests

2: Test command: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304048/build/model1_tests
2: Working Directory: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304048/build
2: Test timeout computed to be: 5
2: Running main() from /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304048/build/_deps/googletest-src/googletest/src/gtest_main.cc
2: [==========] Running 8 tests from 1 test suite.
2: [----------] Global test environment set-up.
2: [----------] 8 tests from StackTest
2: [ RUN      ] StackTest.MaxSizeTest
2: [       OK ] StackTest.MaxSizeTest (0 ms)
2: [ RUN      ] StackTest.PopEmptyStackTest
2: [       OK ] StackTest.PopEmptyStackTest (0 ms)
2: [ RUN      ] StackTest.TopEmptyStackTest
2: [       OK ] StackTest.TopEmptyStackTest (0 ms)
2: [ RUN      ] StackTest.PositiveStackTest
2: [       OK ] StackTest.PositiveStackTest (0 ms)
2: [ RUN      ] StackTest.NegativeStackTest
2: [       OK ] StackTest.NegativeStackTest (0 ms)
2: [ RUN      ] StackTest.MixedStackTest
2: [       OK ] StackTest.MixedStackTest (0 ms)
2: [ RUN      ] StackTest.NegativeMaxSizeTest
2: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304048/test.cpp:67: Failure
2: Expected: IntStack stack(-1) throws an exception of type std::runtime_error.
2:   Actual: it throws std::length_error with description "vector::reserve".
2: 
2: [  FAILED  ] StackTest.NegativeMaxSizeTest (0 ms)
2: [ RUN      ] StackTest.EmptyStackTest
2: [       OK ] StackTest.EmptyStackTest (0 ms)
2: [----------] 8 tests from StackTest (0 ms total)
2: 
2: [----------] Global test environment tear-down
2: [==========] 8 tests from 1 test suite ran. (1 ms total)
2: [  PASSED  ] 7 tests.
2: [  FAILED  ] 1 test, listed below:
2: [  FAILED  ] StackTest.NegativeMaxSizeTest
2: 
2:  1 FAILED TEST
 2/11 Test  #2: model1_tests .....................***Failed    1.63 sec
test 3
      Start  3: model10_tests

3: Test command: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304048/build/model10_tests
3: Working Directory: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304048/build
3: Test timeout computed to be: 5
3: Running main() from /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304048/build/_deps/googletest-src/googletest/src/gtest_main.cc
3: [==========] Running 8 tests from 1 test suite.
3: [----------] Global test environment set-up.
3: [----------] 8 tests from StackTest
3: [ RUN      ] StackTest.MaxSizeTest
3: [       OK ] StackTest.MaxSizeTest (0 ms)
3: [ RUN      ] StackTest.PopEmptyStackTest
3: [       OK ] StackTest.PopEmptyStackTest (0 ms)
3: [ RUN      ] StackTest.TopEmptyStackTest
3: [       OK ] StackTest.TopEmptyStackTest (0 ms)
3: [ RUN      ] StackTest.PositiveStackTest
3: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304048/test.cpp:37: Failure
3: Expected equality of these values:
3:   result
3:     Which is: { 10, 4 }
3:   expected
3:     Which is: { 1, 2, 3, 4 }
3: 
3: [  FAILED  ] StackTest.PositiveStackTest (0 ms)
3: [ RUN      ] StackTest.NegativeStackTest
3: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304048/test.cpp:50: Failure
3: Expected equality of these values:
3:   result
3:     Which is: { -1, -2 }
3:   expected
3:     Which is: { -10, -4, -3, -2 }
3: 
3: [  FAILED  ] StackTest.NegativeStackTest (0 ms)
3: [ RUN      ] StackTest.MixedStackTest
3: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304048/test.cpp:63: Failure
3: Expected equality of these values:
3:   result
3:     Which is: { 3, -4 }
3:   expected
3:     Which is: { -10, -4 }
3: 
3: [  FAILED  ] StackTest.MixedStackTest (0 ms)
3: [ RUN      ] StackTest.NegativeMaxSizeTest
3: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304048/test.cpp:67: Failure
3: Expected: IntStack stack(-1) throws an exception of type std::runtime_error.
3:   Actual: it throws nothing.
3: 
3: [  FAILED  ] StackTest.NegativeMaxSizeTest (0 ms)
3: [ RUN      ] StackTest.EmptyStackTest
3: [       OK ] StackTest.EmptyStackTest (0 ms)
3: [----------] 8 tests from StackTest (0 ms total)
3: 
3: [----------] Global test environment tear-down
3: [==========] 8 tests from 1 test suite ran. (0 ms total)
3: [  PASSED  ] 4 tests.
3: [  FAILED  ] 4 tests, listed below:
3: [  FAILED  ] StackTest.PositiveStackTest
3: [  FAILED  ] StackTest.NegativeStackTest
3: [  FAILED  ] StackTest.MixedStackTest
3: [  FAILED  ] StackTest.NegativeMaxSizeTest
3: 
3:  4 FAILED TESTS
 3/11 Test  #3: model10_tests ....................***Failed    0.55 sec
test 4
      Start  4: model2_tests

4: Test command: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304048/build/model2_tests
4: Working Directory: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304048/build
4: Test timeout computed to be: 5
4: Running main() from /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304048/build/_deps/googletest-src/googletest/src/gtest_main.cc
4: [==========] Running 8 tests from 1 test suite.
4: [----------] Global test environment set-up.
4: [----------] 8 tests from StackTest
4: [ RUN      ] StackTest.MaxSizeTest
4: [       OK ] StackTest.MaxSizeTest (0 ms)
4: [ RUN      ] StackTest.PopEmptyStackTest
4: [       OK ] StackTest.PopEmptyStackTest (0 ms)
4: [ RUN      ] StackTest.TopEmptyStackTest
4: [       OK ] StackTest.TopEmptyStackTest (0 ms)
4: [ RUN      ] StackTest.PositiveStackTest
4: [       OK ] StackTest.PositiveStackTest (0 ms)
4: [ RUN      ] StackTest.NegativeStackTest
4: [       OK ] StackTest.NegativeStackTest (0 ms)
4: [ RUN      ] StackTest.MixedStackTest
4: [       OK ] StackTest.MixedStackTest (0 ms)
4: [ RUN      ] StackTest.NegativeMaxSizeTest
4: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304048/test.cpp:67: Failure
4: Expected: IntStack stack(-1) throws an exception of type std::runtime_error.
4:   Actual: it throws std::length_error with description "vector::reserve".
4: 
4: [  FAILED  ] StackTest.NegativeMaxSizeTest (0 ms)
4: [ RUN      ] StackTest.EmptyStackTest
4: [       OK ] StackTest.EmptyStackTest (0 ms)
4: [----------] 8 tests from StackTest (0 ms total)
4: 
4: [----------] Global test environment tear-down
4: [==========] 8 tests from 1 test suite ran. (0 ms total)
4: [  PASSED  ] 7 tests.
4: [  FAILED  ] 1 test, listed below:
4: [  FAILED  ] StackTest.NegativeMaxSizeTest
4: 
4:  1 FAILED TEST
 4/11 Test  #4: model2_tests .....................***Failed    1.14 sec
test 5
      Start  5: model3_tests

5: Test command: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304048/build/model3_tests
5: Working Directory: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304048/build
5: Test timeout computed to be: 5
5: Running main() from /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304048/build/_deps/googletest-src/googletest/src/gtest_main.cc
5: [==========] Running 8 tests from 1 test suite.
5: [----------] Global test environment set-up.
5: [----------] 8 tests from StackTest
5: [ RUN      ] StackTest.MaxSizeTest
5: [       OK ] StackTest.MaxSizeTest (0 ms)
5: [ RUN      ] StackTest.PopEmptyStackTest
5: [       OK ] StackTest.PopEmptyStackTest (0 ms)
5: [ RUN      ] StackTest.TopEmptyStackTest
5: [       OK ] StackTest.TopEmptyStackTest (0 ms)
5: [ RUN      ] StackTest.PositiveStackTest
5: [       OK ] StackTest.PositiveStackTest (0 ms)
5: [ RUN      ] StackTest.NegativeStackTest
5: [       OK ] StackTest.NegativeStackTest (0 ms)
5: [ RUN      ] StackTest.MixedStackTest
5: [       OK ] StackTest.MixedStackTest (0 ms)
5: [ RUN      ] StackTest.NegativeMaxSizeTest
5: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304048/test.cpp:67: Failure
5: Expected: IntStack stack(-1) throws an exception of type std::runtime_error.
5:   Actual: it throws std::length_error with description "vector::reserve".
5: 
5: [  FAILED  ] StackTest.NegativeMaxSizeTest (0 ms)
5: [ RUN      ] StackTest.EmptyStackTest
5: [       OK ] StackTest.EmptyStackTest (0 ms)
5: [----------] 8 tests from StackTest (0 ms total)
5: 
5: [----------] Global test environment tear-down
5: [==========] 8 tests from 1 test suite ran. (0 ms total)
5: [  PASSED  ] 7 tests.
5: [  FAILED  ] 1 test, listed below:
5: [  FAILED  ] StackTest.NegativeMaxSizeTest
5: 
5:  1 FAILED TEST
 5/11 Test  #5: model3_tests .....................***Failed    0.38 sec
test 6
      Start  6: model4_tests

6: Test command: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304048/build/model4_tests
6: Working Directory: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304048/build
6: Test timeout computed to be: 5
6: Running main() from /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304048/build/_deps/googletest-src/googletest/src/gtest_main.cc
6: [==========] Running 8 tests from 1 test suite.
6: [----------] Global test environment set-up.
6: [----------] 8 tests from StackTest
6: [ RUN      ] StackTest.MaxSizeTest
6: [       OK ] StackTest.MaxSizeTest (0 ms)
6: [ RUN      ] StackTest.PopEmptyStackTest
6: [       OK ] StackTest.PopEmptyStackTest (0 ms)
6: [ RUN      ] StackTest.TopEmptyStackTest
6: [       OK ] StackTest.TopEmptyStackTest (0 ms)
6: [ RUN      ] StackTest.PositiveStackTest
6: [       OK ] StackTest.PositiveStackTest (0 ms)
6: [ RUN      ] StackTest.NegativeStackTest
6: [       OK ] StackTest.NegativeStackTest (0 ms)
6: [ RUN      ] StackTest.MixedStackTest
6: [       OK ] StackTest.MixedStackTest (0 ms)
6: [ RUN      ] StackTest.NegativeMaxSizeTest
6: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304048/test.cpp:67: Failure
6: Expected: IntStack stack(-1) throws an exception of type std::runtime_error.
6:   Actual: it throws std::length_error with description "vector::reserve".
6: 
6: [  FAILED  ] StackTest.NegativeMaxSizeTest (0 ms)
6: [ RUN      ] StackTest.EmptyStackTest
6: [       OK ] StackTest.EmptyStackTest (0 ms)
6: [----------] 8 tests from StackTest (0 ms total)
6: 
6: [----------] Global test environment tear-down
6: [==========] 8 tests from 1 test suite ran. (0 ms total)
6: [  PASSED  ] 7 tests.
6: [  FAILED  ] 1 test, listed below:
6: [  FAILED  ] StackTest.NegativeMaxSizeTest
6: 
6:  1 FAILED TEST
 6/11 Test  #6: model4_tests .....................***Failed    0.48 sec
test 7
      Start  7: model5_tests

7: Test command: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304048/build/model5_tests
7: Working Directory: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304048/build
7: Test timeout computed to be: 5
7: Running main() from /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304048/build/_deps/googletest-src/googletest/src/gtest_main.cc
7: [==========] Running 8 tests from 1 test suite.
7: [----------] Global test environment set-up.
7: [----------] 8 tests from StackTest
7: [ RUN      ] StackTest.MaxSizeTest
7: [       OK ] StackTest.MaxSizeTest (0 ms)
7: [ RUN      ] StackTest.PopEmptyStackTest
7: [       OK ] StackTest.PopEmptyStackTest (0 ms)
7: [ RUN      ] StackTest.TopEmptyStackTest
7: [       OK ] StackTest.TopEmptyStackTest (0 ms)
7: [ RUN      ] StackTest.PositiveStackTest
7: [       OK ] StackTest.PositiveStackTest (0 ms)
7: [ RUN      ] StackTest.NegativeStackTest
7: [       OK ] StackTest.NegativeStackTest (0 ms)
7: [ RUN      ] StackTest.MixedStackTest
7: [       OK ] StackTest.MixedStackTest (0 ms)
7: [ RUN      ] StackTest.NegativeMaxSizeTest
7: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304048/test.cpp:67: Failure
7: Expected: IntStack stack(-1) throws an exception of type std::runtime_error.
7:   Actual: it throws std::length_error with description "vector::reserve".
7: 
7: [  FAILED  ] StackTest.NegativeMaxSizeTest (0 ms)
7: [ RUN      ] StackTest.EmptyStackTest
7: [       OK ] StackTest.EmptyStackTest (0 ms)
7: [----------] 8 tests from StackTest (0 ms total)
7: 
7: [----------] Global test environment tear-down
7: [==========] 8 tests from 1 test suite ran. (0 ms total)
7: [  PASSED  ] 7 tests.
7: [  FAILED  ] 1 test, listed below:
7: [  FAILED  ] StackTest.NegativeMaxSizeTest
7: 
7:  1 FAILED TEST
 7/11 Test  #7: model5_tests .....................***Failed    0.42 sec
test 8
      Start  8: model6_tests

8: Test command: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304048/build/model6_tests
8: Working Directory: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304048/build
8: Test timeout computed to be: 5
8: Running main() from /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304048/build/_deps/googletest-src/googletest/src/gtest_main.cc
8: [==========] Running 8 tests from 1 test suite.
8: [----------] Global test environment set-up.
8: [----------] 8 tests from StackTest
8: [ RUN      ] StackTest.MaxSizeTest
8: [       OK ] StackTest.MaxSizeTest (0 ms)
8: [ RUN      ] StackTest.PopEmptyStackTest
8: [       OK ] StackTest.PopEmptyStackTest (0 ms)
8: [ RUN      ] StackTest.TopEmptyStackTest
8: [       OK ] StackTest.TopEmptyStackTest (0 ms)
8: [ RUN      ] StackTest.PositiveStackTest
8: [       OK ] StackTest.PositiveStackTest (0 ms)
8: [ RUN      ] StackTest.NegativeStackTest
8: [       OK ] StackTest.NegativeStackTest (0 ms)
8: [ RUN      ] StackTest.MixedStackTest
8: [       OK ] StackTest.MixedStackTest (0 ms)
8: [ RUN      ] StackTest.NegativeMaxSizeTest
8: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304048/test.cpp:67: Failure
8: Expected: IntStack stack(-1) throws an exception of type std::runtime_error.
8:   Actual: it throws nothing.
8: 
8: [  FAILED  ] StackTest.NegativeMaxSizeTest (0 ms)
8: [ RUN      ] StackTest.EmptyStackTest
8: [       OK ] StackTest.EmptyStackTest (0 ms)
8: [----------] 8 tests from StackTest (0 ms total)
8: 
8: [----------] Global test environment tear-down
8: [==========] 8 tests from 1 test suite ran. (0 ms total)
8: [  PASSED  ] 7 tests.
8: [  FAILED  ] 1 test, listed below:
8: [  FAILED  ] StackTest.NegativeMaxSizeTest
8: 
8:  1 FAILED TEST
 8/11 Test  #8: model6_tests .....................***Failed    0.58 sec
test 9
      Start  9: model7_tests

9: Test command: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304048/build/model7_tests
9: Working Directory: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304048/build
9: Test timeout computed to be: 5
9: Running main() from /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304048/build/_deps/googletest-src/googletest/src/gtest_main.cc
9: [==========] Running 8 tests from 1 test suite.
9: [----------] Global test environment set-up.
9: [----------] 8 tests from StackTest
9: [ RUN      ] StackTest.MaxSizeTest
9: [       OK ] StackTest.MaxSizeTest (0 ms)
9: [ RUN      ] StackTest.PopEmptyStackTest
9: [       OK ] StackTest.PopEmptyStackTest (0 ms)
9: [ RUN      ] StackTest.TopEmptyStackTest
9: [       OK ] StackTest.TopEmptyStackTest (0 ms)
9: [ RUN      ] StackTest.PositiveStackTest
9: [       OK ] StackTest.PositiveStackTest (0 ms)
9: [ RUN      ] StackTest.NegativeStackTest
9: [       OK ] StackTest.NegativeStackTest (0 ms)
9: [ RUN      ] StackTest.MixedStackTest
9: [       OK ] StackTest.MixedStackTest (0 ms)
9: [ RUN      ] StackTest.NegativeMaxSizeTest
9: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304048/test.cpp:67: Failure
9: Expected: IntStack stack(-1) throws an exception of type std::runtime_error.
9:   Actual: it throws nothing.
9: 
9: [  FAILED  ] StackTest.NegativeMaxSizeTest (0 ms)
9: [ RUN      ] StackTest.EmptyStackTest
9: [       OK ] StackTest.EmptyStackTest (0 ms)
9: [----------] 8 tests from StackTest (0 ms total)
9: 
9: [----------] Global test environment tear-down
9: [==========] 8 tests from 1 test suite ran. (0 ms total)
9: [  PASSED  ] 7 tests.
9: [  FAILED  ] 1 test, listed below:
9: [  FAILED  ] StackTest.NegativeMaxSizeTest
9: 
9:  1 FAILED TEST
 9/11 Test  #9: model7_tests .....................***Failed    0.43 sec
test 10
      Start 10: model8_tests

10: Test command: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304048/build/model8_tests
10: Working Directory: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304048/build
10: Test timeout computed to be: 5
10: Running main() from /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304048/build/_deps/googletest-src/googletest/src/gtest_main.cc
10: [==========] Running 8 tests from 1 test suite.
10: [----------] Global test environment set-up.
10: [----------] 8 tests from StackTest
10: [ RUN      ] StackTest.MaxSizeTest
10: [       OK ] StackTest.MaxSizeTest (0 ms)
10: [ RUN      ] StackTest.PopEmptyStackTest
10: [       OK ] StackTest.PopEmptyStackTest (0 ms)
10: [ RUN      ] StackTest.TopEmptyStackTest
10: [       OK ] StackTest.TopEmptyStackTest (0 ms)
10: [ RUN      ] StackTest.PositiveStackTest
10: [       OK ] StackTest.PositiveStackTest (0 ms)
10: [ RUN      ] StackTest.NegativeStackTest
10: [       OK ] StackTest.NegativeStackTest (0 ms)
10: [ RUN      ] StackTest.MixedStackTest
10: [       OK ] StackTest.MixedStackTest (0 ms)
10: [ RUN      ] StackTest.NegativeMaxSizeTest
10: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304048/test.cpp:67: Failure
10: Expected: IntStack stack(-1) throws an exception of type std::runtime_Errors while running CTest
Output from these tests are in: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304048/build/Testing/Temporary/LastTest.log
Use "--rerun-failed --output-on-failure" to re-run the failed cases verbosely.
error.
10:   Actual: it throws nothing.
10: 
10: [  FAILED  ] StackTest.NegativeMaxSizeTest (0 ms)
10: [ RUN      ] StackTest.EmptyStackTest
10: [       OK ] StackTest.EmptyStackTest (0 ms)
10: [----------] 8 tests from StackTest (0 ms total)
10: 
10: [----------] Global test environment tear-down
10: [==========] 8 tests from 1 test suite ran. (0 ms total)
10: [  PASSED  ] 7 tests.
10: [  FAILED  ] 1 test, listed below:
10: [  FAILED  ] StackTest.NegativeMaxSizeTest
10: 
10:  1 FAILED TEST
10/11 Test #10: model8_tests .....................***Failed    0.40 sec
test 11
      Start 11: model9_tests

11: Test command: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304048/build/model9_tests
11: Working Directory: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304048/build
11: Test timeout computed to be: 5
11: Running main() from /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304048/build/_deps/googletest-src/googletest/src/gtest_main.cc
11: [==========] Running 8 tests from 1 test suite.
11: [----------] Global test environment set-up.
11: [----------] 8 tests from StackTest
11: [ RUN      ] StackTest.MaxSizeTest
11: [       OK ] StackTest.MaxSizeTest (0 ms)
11: [ RUN      ] StackTest.PopEmptyStackTest
11: [       OK ] StackTest.PopEmptyStackTest (0 ms)
11: [ RUN      ] StackTest.TopEmptyStackTest
11: [       OK ] StackTest.TopEmptyStackTest (0 ms)
11: [ RUN      ] StackTest.PositiveStackTest
11: [       OK ] StackTest.PositiveStackTest (0 ms)
11: [ RUN      ] StackTest.NegativeStackTest
11: [       OK ] StackTest.NegativeStackTest (0 ms)
11: [ RUN      ] StackTest.MixedStackTest
11: [       OK ] StackTest.MixedStackTest (0 ms)
11: [ RUN      ] StackTest.NegativeMaxSizeTest
11: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304048/test.cpp:67: Failure
11: Expected: IntStack stack(-1) throws an exception of type std::runtime_error.
11:   Actual: it throws nothing.
11: 
11: [  FAILED  ] StackTest.NegativeMaxSizeTest (0 ms)
11: [ RUN      ] StackTest.EmptyStackTest
11: [       OK ] StackTest.EmptyStackTest (0 ms)
11: [----------] 8 tests from StackTest (0 ms total)
11: 
11: [----------] Global test environment tear-down
11: [==========] 8 tests from 1 test suite ran. (0 ms total)
11: [  PASSED  ] 7 tests.
11: [  FAILED  ] 1 test, listed below:
11: [  FAILED  ] StackTest.NegativeMaxSizeTest
11: 
11:  1 FAILED TEST
11/11 Test #11: model9_tests .....................***Failed    0.51 sec

0% tests passed, 11 tests failed out of 11

Total Test time (real) =   6.54 sec

The following tests FAILED:
	  1 - incorrect_solution_tests (Not Run)
	  2 - model1_tests (Failed)
	  3 - model10_tests (Failed)
	  4 - model2_tests (Failed)
	  5 - model3_tests (Failed)
	  6 - model4_tests (Failed)
	  7 - model5_tests (Failed)
	  8 - model6_tests (Failed)
	  9 - model7_tests (Failed)
	 10 - model8_tests (Failed)
	 11 - model9_tests (Failed)
Test project /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304048/build
      Start  1: incorrect_solution_tests
Could not find executable /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304048/build/incorrect_solution_tests
Looked in the following places:
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304048/build/incorrect_solution_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304048/build/incorrect_solution_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304048/build/Release/incorrect_solution_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304048/build/Release/incorrect_solution_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304048/build/Debug/incorrect_solution_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304048/build/Debug/incorrect_solution_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304048/build/MinSizeRel/incorrect_solution_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304048/build/MinSizeRel/incorrect_solution_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304048/build/RelWithDebInfo/incorrect_solution_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304048/build/RelWithDebInfo/incorrect_solution_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304048/build/Deployment/incorrect_solution_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304048/build/Deployment/incorrect_solution_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304048/build/Development/incorrect_solution_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304048/build/Development/incorrect_solution_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304048/build/incorrect_solution_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304048/build/incorrect_solution_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304048/build/Release/incorrect_solution_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304048/build/Release/incorrect_solution_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304048/build/Debug/incorrect_solution_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304048/build/Debug/incorrect_solution_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304048/build/MinSizeRel/incorrect_solution_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304048/build/MinSizeRel/incorrect_solution_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304048/build/RelWithDebInfo/incorrect_solution_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304048/build/RelWithDebInfo/incorrect_solution_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304048/build/Deployment/incorrect_solution_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304048/build/Deployment/incorrect_solution_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304048/build/Development/incorrect_solution_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304048/build/Development/incorrect_solution_tests
Unable to find executable: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304048/build/incorrect_solution_tests
 1/11 Test  #1: incorrect_solution_tests .........***Not Run   0.00 sec
      Start  2: model1_tests
 2/11 Test  #2: model1_tests .....................***Failed    0.02 sec
      Start  3: model10_tests
 3/11 Test  #3: model10_tests ....................***Failed    0.02 sec
      Start  4: model2_tests
 4/11 Test  #4: model2_tests .....................***Failed    0.02 sec
      Start  5: model3_tests
 5/11 Test  #5: model3_tests .....................***Failed    0.02 sec
      Start  6: model4_tests
 6/11 Test  #6: model4_tests .....................***Failed    0.02 sec
      Start  7: model5_tests
 7/11 Test  #7: model5_tests .....................***Failed    0.02 sec
      Start  8: model6_tests
 8/11 Test  #8: model6_tests .....................***Failed    0.02 sec
      Start  9: model7_tests
 9/11 Test  #9: model7_tests .....................***Failed    0.02 sec
      Start 10: model8_tests
10/11 Test #10: model8_tests .....................***Failed    0.02 sec
      Start 11: model9_tests
11/11 Test #11: model9_tests .....................***Failed    0.02 sec

0% tests passed, 11 tests failed out of 11

Total Test time (real) =   0.23 sec

The following tests FAILED:
	  1 - incorrect_solution_tests (Not Run)
	  2 - model1_tests (Failed)
	  3 - model10_tests (Failed)
	  4 - model2_tests (Failed)
	  5 - model3_tests (Failed)
	  6 - model4_tests (Failed)
	  7 - model5_tests (Failed)
	  8 - model6_tests (Failed)
	  9 - model7_tests (Failed)
	 10 - model8_tests (Failed)
	 11 - model9_tests (Failed)
Errors while running CTest
Output from these tests are in: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/304048/build/Testing/Temporary/LastTest.log
Use "--rerun-failed --output-on-failure" to re-run the failed cases verbosely.
